# Build stage (using a multi-stage build)
FROM maven:3.8.6-amazoncorretto-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# Runtime stage (smaller image)
FROM amazoncorretto:17-alpine-jdk

WORKDIR /app

COPY --from=build /app/target/my-app.jar /app/my-app.jar  

EXPOSE 8080

# Set the entrypoint to run the Spring Boot app
CMD ["java", "-jar", "my-app.jar"]

# Optional: Add a healthcheck (highly recommended for production)
HEALTHCHECK --interval=30s --timeout=10s --retries=5 --start-period=60s CMD ["java", "-jar", "app.jar", "--spring.boot.actuator.health.livenessstate.enabled=true"]


#build docker buildx build -t login-backend-app -f ./DockerFile .
#run docker run -p 8080:8080 login-backend-app